# Generated by Django 4.2.5 on 2023-10-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
